# RAG System Configuration Template
# Customize this file for each client deployment

# Company/Business Information
company:
  name: "Your Company Name"
  description: "Brief description of your business"
  website: "https://yourcompany.com"
  contact:
    email: "contact@yourcompany.com"
    phone: "+1234567890"
    additional_phone: ""

# Language and Localization
language:
  primary: "en"  # en, it, es, fr, de, etc.
  assistant_name: "AI Assistant"

# System Prompt Configuration
system_prompt:
  role: "professional assistant"  # professional, friendly, technical, sales, support
  instructions: |
    You are an AI assistant for {company_name}.

    Your role:
    - Provide helpful information based on the company's knowledge base
    - Answer questions clearly and accurately
    - Be professional and courteous
    - Use ONLY information from the provided context
    - If information is not in the context, say so clearly

    Important rules:
    - Only answer based on the provided context
    - Do not make up information
    - Maintain a {role} tone
    - Always respond in {language}

# RAG Parameters
rag:
  chunk_size: 500  # characters per chunk
  chunk_overlap: 50  # overlap between chunks
  top_k: 3  # number of chunks to retrieve
  batch_size: 32  # embedding batch size

# Embedding Model
embedding:
  model: "paraphrase-multilingual-MiniLM-L12-v2"
  dimension: 384

# LLM Configuration (DeepSeek)
llm:
  provider: "deepseek"
  model: "deepseek-chat"
  temperature: 0.3
  max_tokens: 500
  api_base: "https://api.deepseek.com/v1"

# Web UI Customization
ui:
  title: "Knowledge Base Assistant"
  page_icon: "🤖"
  theme: "light"  # light or dark
  show_sources: true
  show_retrieval_scores: false  # for debugging
  welcome_message: |
    Welcome! Ask me anything about {company_name}.

    I can help you with information from our knowledge base.

# Data Sources
data:
  input_folder: "data/sample"  # Use sample data for demo
  supported_formats:
    - "txt"
    - "pdf"
    - "docx"
    - "md"
  web_scraping:
    enabled: false
    urls: []

# Deployment
deployment:
  host: "0.0.0.0"
  port: 8501
  debug: false
